# Generated by Django 4.2.14 on 2024-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Поле ввода города',
                'verbose_name_plural': 'Поля ввода города',
            },
        ),
    ]
