# Generated by Django 4.2.14 on 2024-07-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
